kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane        
    extraPortMappings:      
      - containerPort: 30443        
        hostPort: 8080        
        protocol: TCP        
        listenAddress: "0.0.0.0"
  - role: worker    
